# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.1.2

# Mod Properties
mod_version=1.2.1
maven_group=slexom.vf
archives_name=animal_feeding_trough

# Architectury
enabled_platforms=fabric,neoforge

# Fabric
fabric_loader_version=0.19.2
fabric_api_version=0.146.1+26.1.2

# NeoForge
neoforge_version=26.1.2.64-beta
fabric.loom.disableObfuscation=true